permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: redcarpet

# author info
author:
  name: Hong Wang
  email: ama.hong.wang@gmail.com
  github: https://github.com/polyHong


# Site settings
title: Hong's Blog
email: ama.hong.wang@gmail.com
description: Hong's personal blog
url: http://hitwanghong.com  # the base hostname & protocol for your cite
rss_url: /pages/feed.xml


# avatar and Favicon
gavatar: /public/img/foot.jpg
favicon: /public/img/boy.jpg


# google analytics 设置
ga:
  id: UA-96196163-1
  url: hitwanghong.com

# disqus 设置
disqus:
  shortname: polyhong


# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  newest: 最新文章
  archive: 归档